"""remove_seriesresulttable

Revision ID: 01f6f86d7e41
Revises: 8856f2f1790c
Create Date: 2016-10-31 13:31:00.401103

"""

# revision identifiers, used by Alembic.
revision = '01f6f86d7e41'
down_revision = '8856f2f1790c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_result')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seriesid', sa.INTEGER(), nullable=True),
    sa.Column('seriesclassid', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('results', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
