"""event owner

Revision ID: 0241f3e488ad
Revises: 438c8cd9c7a6
Create Date: 2017-10-04 16:35:30.799748

"""

# revision identifiers, used by Alembic.
revision = '0241f3e488ad'
down_revision = '438c8cd9c7a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ltuserid', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('replacedbyid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'replacedbyid')
    op.drop_column('event', 'ltuserid')
    ### end Alembic commands ###
