"""empty message

Revision ID: 18b69cd2a21f
Revises: 3aafeddc158f
Create Date: 2016-10-14 20:41:43.401425

"""

# revision identifiers, used by Alembic.
revision = '18b69cd2a21f'
down_revision = '3aafeddc158f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_team_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('classids', sa.String(), nullable=True),
    sa.Column('scoremethod', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.Column('teamclassid', sa.Integer(), nullable=True),
    sa.Column('teamname_short', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_result')
    op.drop_table('event_team_class')
    ### end Alembic commands ###
