"""users base

Revision ID: 438c8cd9c7a6
Revises: fd598f7e0a5e
Create Date: 2017-10-02 15:13:13.673128

"""

# revision identifiers, used by Alembic.
revision = '438c8cd9c7a6'
down_revision = 'fd598f7e0a5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.Column('salt', sa.String(length=32), nullable=True),
    sa.Column('isMod', sa.Boolean(), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
