"""empty message

Revision ID: 58cf5bc7866e
Revises: 18b69cd2a21f
Create Date: 2016-10-15 12:05:24.866570

"""

# revision identifiers, used by Alembic.
revision = '58cf5bc7866e'
down_revision = '18b69cd2a21f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_result', sa.Column('resultids', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_result', 'resultids')
    ### end Alembic commands ###
