"""series tables

Revision ID: 5d1e67702296
Revises: 01f36622c757
Create Date: 2016-10-29 14:21:08.281576

"""

# revision identifiers, used by Alembic.
revision = '5d1e67702296'
down_revision = '01f36622c757'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('eventids', sa.String(), nullable=True),
    sa.Column('scoremethod', sa.String(), nullable=True),
    sa.Column('scoreeventscount', sa.Integer(), nullable=True),
    sa.Column('scoreeventsneeded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seriesid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('eventids', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seriesid', sa.Integer(), nullable=True),
    sa.Column('seriesclassid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('results', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_result')
    op.drop_table('series_class')
    op.drop_table('series')
    ### end Alembic commands ###
