"""event isProcessed

Revision ID: 722212d210e8
Revises: 0241f3e488ad
Create Date: 2017-10-04 18:19:19.145483

"""

# revision identifiers, used by Alembic.
revision = '722212d210e8'
down_revision = '0241f3e488ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('isProcessed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'isProcessed')
    ### end Alembic commands ###
