"""seriesclass_type

Revision ID: 8856f2f1790c
Revises: d117be359e6f
Create Date: 2016-10-31 13:01:48.703415

"""

# revision identifiers, used by Alembic.
revision = '8856f2f1790c'
down_revision = 'd117be359e6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series_class', sa.Column('classtype', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series_class', 'classtype')
    ### end Alembic commands ###
