"""empty message

Revision ID: 9e4b007acbe1
Revises: 01f6f86d7e41
Create Date: 2017-05-19 21:13:12.931964

"""

# revision identifiers, used by Alembic.
revision = '9e4b007acbe1'
down_revision = '01f6f86d7e41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_result', sa.Column('ScoreO_net', sa.Integer(), nullable=True))
    op.add_column('person_result', sa.Column('ScoreO_penalty', sa.Integer(), nullable=True))
    op.add_column('person_result', sa.Column('ScoreO_points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_result', 'ScoreO_points')
    op.drop_column('person_result', 'ScoreO_penalty')
    op.drop_column('person_result', 'ScoreO_net')
    ### end Alembic commands ###
