"""series tiebreak

Revision ID: d117be359e6f
Revises: fb3dcbfa6111
Create Date: 2016-10-30 13:44:08.906267

"""

# revision identifiers, used by Alembic.
revision = 'd117be359e6f'
down_revision = 'fb3dcbfa6111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('scoretiebreak', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'scoretiebreak')
    ### end Alembic commands ###
