"""empty message

Revision ID: d2383353f59b
Revises: fb29540d5ce7
Create Date: 2016-10-27 20:11:18.256920

"""

# revision identifiers, used by Alembic.
revision = 'd2383353f59b'
down_revision = 'fb29540d5ce7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_result', sa.Column('numfinishes', sa.Integer(), nullable=True))
    op.add_column('team_result', sa.Column('numstarts', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_result', 'numstarts')
    op.drop_column('team_result', 'numfinishes')
    ### end Alembic commands ###
