"""empty message

Revision ID: fb29540d5ce7
Revises: cea70ae714bc
Create Date: 2016-10-24 19:25:34.910374

"""

# revision identifiers, used by Alembic.
revision = 'fb29540d5ce7'
down_revision = 'cea70ae714bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Alter column fails for my SQLite backend
    # op.alter_column('event', 'date',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    ### end Alembic commands ###

    with op.batch_alter_table("event") as batch_op:
        batch_op.alter_column('date',
                              existing_type=sa.VARCHAR(),
                              type_=sa.DateTime(),
                              existing_nullable=True
        )

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event') as batch_op:
        batch_op.alter_column('date',
                              existing_type=sa.DateTime(),
                              type_=sa.VARCHAR(),
                              existing_nullable=True
        )
    ### end Alembic commands ###
