"""seriesclass edits

Revision ID: fb3dcbfa6111
Revises: 5d1e67702296
Create Date: 2016-10-30 11:16:42.316744

"""

# revision identifiers, used by Alembic.
revision = 'fb3dcbfa6111'
down_revision = '5d1e67702296'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series_class', sa.Column('eventclassids', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series_class', 'eventclassids')
    ### end Alembic commands ###
